repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.5
  hooks:
    # Run the linter.
    - id: ruff
      # args: [ --fix ]
      args: [ --config, ./applications/app/function_code/api/pyproject.toml ]
    # Run the formatter.
    # - id: ruff-format
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: /home/jar0/.pyenv/versions/3.11.9/bin/isort
      # args: [--settings-path, ./applications/app/function_code/api/.isort.cfg ]
      args: [--check, --diff]
      language: python
# - repo: https://github.com/pycqa/isort
#   rev: 5.11.2
#   hooks:
#     - id: isort
#       name: isort
#       args: [--show, --diff]
