"""create tables

Revision ID: b1205ae47044
Revises: 
Create Date: 2025-10-25 15:51:05.756454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1205ae47044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('disease_category', sa.Enum(), nullable=False),
    sa.Column('date_detected', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity_level', sa.Enum(), nullable=False),
    sa.Column('lab_results', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('treatment_status', sa.Enum(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Interval(), nullable=True),
    sa.Column('gender', sa.Enum(), nullable=False),
    sa.Column('medical_record_number', sa.Integer(), nullable=False),
    sa.Column('patient_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('emergency_contact', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_record_number')
    )
    op.create_table('reporter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('organization_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['reporter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('user')
    op.drop_table('reporter')
    op.drop_table('patient')
    op.drop_table('disease')
    # ### end Alembic commands ###
