"""update tables

Revision ID: c62be8a2c51f
Revises:
Create Date: 2025-10-26 11:31:44.315896

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c62be8a2c51f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key("patient_id to patient.id", 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key("disease_id to disease.id", 'disease', ['disease_iq'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key("updated_by to reporter.id", 'reporter', ['updated_by'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key("reporter_id to reporter.id", 'reporter', ['reporter_id'], ['id'])


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint("patient_id to patient.id", type_='foreignkey')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint("disease_id to disease.id", type_='foreignkey')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint("updated_by to reporter.id", type_='foreignkey')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint("reporter_id to reporter.id", type_='foreignkey')

    # ### end Alembic commands ###
